routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Models\Product;

Route::get('/', [SiteController::class, 'index']);
Route::get('/product', [SiteController::class, 'show']);
Route::middleware('auth')->group(function () {
    Route::get('/home', [SiteController::class, 'home']);



    Route::prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function () {

        Route::get('/', [AdminController::class, 'index'])->name('index');

        Route::resource('users', UserController::class);
        Route::resource('categories', CategoryController::class);

        Route::get('products/{product}/media', [\App\Http\Controllers\Admin\ProductController::class, 'media'])->name('products.media');
        Route::put('products/{product}/media', [\App\Http\Controllers\Admin\ProductController::class, 'mediaUpload'])->name('products.upload');
        Route::delete('products/{product}/media', [\App\Http\Controllers\Admin\ProductController::class, 'removeMedia'])->name('products.removeMedia');
        Route::resource('products', ProductController::class);
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'contact',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class UserController extends Controller
{

    public $roles = [
        'User',
        'Admin',
        'Editor',
    ];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::simplepaginate(10); 
        return view('admin.users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = $this->roles;

        return view('admin.users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|min:6',
            'contact' => 'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:10',
            'role' => ['required', Rule::in($this->roles)],
            
        ]);

        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password),
            'contact' => $request->contact,
            'role' => $request->role,
        ]);

        return redirect()->route('admin.users.index')
                ->with('success', 'User Created Successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = $this->roles;

        return view('admin.users.edit', compact('user','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users,email,' . $user->id,
            'password' => 'nullable|min:6',
            'contact' => 'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:10,' . $user->id,
            'role' => ['required', Rule::in($this->roles)],
        ]);

        $user->name = $request->name;
        $user->email = $request->email;
        $user->contact = $request->contact;
        $user->role = $request->role;

        if(!empty($request->password)){
            $user->password = bcrypt($request->password);
        }

        $user->save();

        return redirect()->route('admin.users.index')
                ->with('success', 'User Updated Successfully!');
    }
    

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('admin.users.index')
        ->with('success', 'User Deleted Successfully!');
    }
}

resources/views/admin/users/create.blade.php
@extends('adminlte::page')

@section('title', 'Create New User')

@section('plugins.Select2', true)

@section('js')

<script>
    $(document).ready(function(){
        $('#role').select2{
            minimumResultForSearch: Infinity
        };
    });
</script>

@endsection

@section('content')

<x-alert />
 
<div class="card">
      <div class="card-header ">
          <h3 class="card-title text-bold">Create New User</h3>
          <div class="card-tools">
            <a href="{{ route('admin.users.index') }}" class="btn btn-primary btn-sm">
            Go Back
        </a>
          </div>
      </div>
      <div class="card-body  " >
           <form action="{{ route('admin.users.store') }}" method="POST">
             @csrf

             <x-input
             field="name"
             text="Name"
             />

             <x-input
             field="email"
             text="Email"
             />

             <x-input
             field="contact"
             text="Contact"
             />

             <x-input
             field="password"
             text="Password"
             type="password"
             />
                <div class="form-group">
                    <label for="role">Role</label>
                    <select name="role" id="role" class="form-control @error('role') is-invalid @enderror">
                        @foreach ($roles as $role )
                        <option value="{{ $role }}">{{ $role }}</option>
                        @endforeach
                    </select>

                    @error('role')
                    <small class="form-text text-danger">{{ $message }}</small>   
                    @enderror

                </div>

                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-fw fa-save mr-1"></i>
                    Save
                </button>

            </form>
        
        </div>
  </div>

  @stop

resources/views/admin/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'Update User')

@section('plugins.Select2', true)

@section('js')

<script>
    $(document).ready(function(){
        $('#role').select2{
            minimumResultForSearch: Infinity
        };
    });
</script>

@endsection

@section('content')

<x-alert />
 
<div class="card">
      <div class="card-header ">
          <h3 class="card-title text-bold">Update User</h3>
          <div class="card-tools">
            <a href="{{ route('admin.users.create') }}" class="btn btn-primary btn-sm">
            Go Back
        </a>
          </div>
      </div>
      <div class="card-body  " >
           <form action="{{ route('admin.users.update', $user->id) }}" method="Post">
             @csrf
             @method('PUT')

             <x-input
             field="name"
             text="Name"
             :current="$user->name"
             />

             <x-input
             field="email"
             text="Email"
             :current="$user->email"
             />

             <x-input
             field="contact"
             text="Contact"
             :current="$user->contact"
             />

             <x-input
             field="password"
             text="Password"
             type="password"
             />
                <div class="form-group">
                    <label for="role">Role</label>
                    <select name="role" id="role" class="form-control @error('role') is-invalid @enderror">
                        @foreach ($roles as $role )
                        <option value="{{ $role }}" @if($role == $user->role) selected @endif>
                            {{ $role }}</option>
                        @endforeach
                    </select>

                    @error('role')
                    <small class="form-text text-danger">{{ $message }}</small>   
                    @enderror

                </div>

                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-fw fa-save mr-1"></i>
                    Save
                </button>

            </form>
        
        </div>
  </div>

  @stop

resources/views/admin/users/index.blade.php
@extends('adminlte::page')

@section('title', 'All Users')

@section('content')

<x-alert />
<x-delete />
 
<div class="card">
      <div class="card-header ">
          <h3 class="card-title text-bold">All Users</h3>
          <div class="card-tools">
            <a href="{{ route('admin.users.create') }}" class="btn btn-primary btn-sm">
            Add New User
        </a>
          </div>
      </div>
      <div class="card-body p-0 " >
          <table class="table table-bordered table-striped">
              <thead class="thead-dark">
                  <tr>
                      <th>Id</th>
                      <th>Name</th>
                      <th>Email</th>
                      <th>Role</th>
                      <th>Contact Number</th>
                      <th>Action</th>
                  </tr>
              </thead>
              <tbody>
                  @foreach($users as $user)   
                  <tr>
                      <td> {{ $user->id }}</td>
                      <td> {{ $user->name }}</td>
                      <td> {{ $user->email }}</td>
                      <td> {{ $user->role }}</td>
                      <td> {{ $user->contact }}</td>
                      <td>
                          <a href="{{ route('admin.users.show', $user->id) }} " class="btn btn-secondary btn-sm">
                            Details
                        </a>

                        <a href="{{ route('admin.users.edit', $user->id) }} " class="btn btn-primary btn-sm">
                            Edit
                        </a>

                        <button class="btn btn-danger btn-sm" onclick="confirmDelete({{ $user->id }})">
                            Delete
                        </button>

                        <form id="delete-form-{{ $user->id }}" action="{{ route('admin.users.destroy', $user->id) }}" method="POST" style="display:none">
                            @csrf @method('DELETE')
                        </form>
                      </td>
                  </tr>                   
                  @endforeach
              </tbody>
          </table>
        </div>
        @if ($users->perPage() > $user->total)

       <div class="card-footer">
        {{ $users->links() }}
       </div>
        
        @endif
  </div>
@stop

resources/views/admin/users/show.blade.php
@extends('adminlte::page')

@section('title', 'User Details')

@section('content')

 
<div class="card">
      <div class="card-header ">
          <h3 class="card-title text-bold">User Information</h3>
          <div class="card-tools">
            <a href="{{ route('admin.users.index') }}" class="btn btn-primary btn-sm">
            Go Back
        </a>
          </div>
      </div>
      <div class="card-body p-0 " >
          
          <table class="table table-bordered table-striped">
            <tr>
                <th width="15%">ID</th>
                <td>{{ $user->id }}</td>
            </tr>
              <tr>
                  <th>Name</th>
                  <td>{{ $user->name }}</td>
              </tr>
              <tr>
                <th>Email</th>
                <td>{{ $user->email }}</td>
            </tr>
            <tr>
                <th>Contact</th>
                <td>{{ $user->contact }}</td>
            </tr>
            <tr>
                <th>Role</th>
                <td>{{ $user->role }}</td>
            </tr>

          </table>
        
      </div>
  </div>

  @stop