routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Models\Product;

Route::get('/', [SiteController::class, 'index']);
Route::get('/product', [SiteController::class, 'show']);
Route::middleware('auth')->group(function () {
    Route::get('/home', [SiteController::class, 'home']);



    Route::prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function () {

        Route::get('/', [AdminController::class, 'index'])->name('index');

        Route::resource('users', UserController::class);
        Route::resource('categories', CategoryController::class);

        Route::get('products/{product}/media', [\App\Http\Controllers\Admin\ProductController::class, 'media'])->name('products.media');
        Route::put('products/{product}/media', [\App\Http\Controllers\Admin\ProductController::class, 'mediaUpload'])->name('products.upload');
        Route::delete('products/{product}/media', [\App\Http\Controllers\Admin\ProductController::class, 'removeMedia'])->name('products.removeMedia');
        Route::resource('products', ProductController::class);
    });
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function medias()
    {
        return $this->belongsToMany(Media::class);
    }

    /**
     * Show Product Cover Image
     *
     * @return void
     */
    public function getImageAttribute()
    {
        $image = $this->medias->first();
        if ($image)
            return '/storage/' . $image->path;
        else
            return '/images/not-found.png';
    }

    /**
     * Show All Images for that Media
     *
     * @return void
     */
    public function getImagesAttribute()
    {
        $images = $this->medias;
        $all_images = $images->map(function ($image) {
            return $image->path;
        });

        return $all_images;
    }


}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Media;
use App\Models\Product;
use App\Models\MediaProduct;
use Illuminate\Http\Request;
use App\Services\MediaService;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $products = Product::Paginate(30);

        return view('admin.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => ['required'],
            'price' => ['required', 'numeric', 'gt:0'],
            'description' => ['nullable'],
        ]);

        $product = Product::create($request->only('name', 'price', 'description'));

        return redirect()->route('admin.products.index')
            ->with('success', 'Product created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('admin.products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('admin.products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $data = $request->validate([
            'name' => ['required'],
            'price' => ['required', 'numeric', 'gt:0'],
            'description' => ['nullable'],
        ]);

        $product->update($data);

        return redirect()->route('admin.products.index')
            ->with('success', 'Product updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('admin.products.index')
        ->with('success', 'Product deleted successfully!');
    }


    public function media(Product $product)
    {
        return view('admin.products.media', compact('product'));
    }

    public function mediaUpload(Request $request, Product $product)
    {
        $request->validate([
            'image' => 'required|image|mimes:png,gif,jpeg',
        ]);

        $media_id = MediaService::upload($request->file('image'), "products");

        $product->medias()->attach(Media::find($media_id));

        return redirect()
            ->route('admin.products.media', $product->id)
            ->with('success', 'File uploaded successfully!');
    }

    public function removeMedia(Request $request, Product $product)
    {
        $request->validate([
            'media_id' => 'required|exists:media,id',
        ]);

        $media = Media::find($request->media_id);

        $mp = MediaProduct::where('media_id', $media->id)->where('product_id', $product->id)->first();

        if ($mp) {
            Storage::delete("public/" . $media->path);
            $mp->delete();
            $media->delete();
        }

        return redirect()
            ->route('admin.products.media', $product->id)
            ->with('success', 'File removed successfully!');
    }

}

resources/views/admin/products/create.blade.php
@extends('adminlte::page')

@section('title', 'Create New Product')

@section('plugins.Select2', true)

@section('content')

<x-alert />

<div class="card">
      <div class="card-header ">
          <h3 class="card-title text-bold">Create New Product</h3>
          <div class="card-tools">
            <a href="{{ route('admin.products.index') }}" class="btn btn-primary btn-sm">
            Go Back
        </a>
          </div>
      </div>
      <div class="card-body" >
           <form action="{{ route('admin.products.store') }}" method="POST">
             @csrf

             <div class="form-group">
                <label for="name">Name</label>
                <input
                    type="text"
                    name="name" id="name"
                    value="{{ old('name') ?? '' }}"
                    class="form-control @error('name') is-invalid @enderror"
                >
                @error('name')
                <small class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="price">Price</label>
                <input
                    type="number"
                    name="price" id="price"
                    value="{{ old('price') ?? '' }}"
                    class="form-control @error('price') is-invalid @enderror"
                >
                @error('price')
                <small class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="description">Description</label>
                <textarea
                    name="description" id="description"
                    value="{{ old('description') ?? '' }}"
                    class="form-control @error('description') is-invalid @enderror"
                ></textarea>
                @error('description')
                <small class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-fw fa-save mr-1"></i>
                    Save
                </button>

            </form>

        </div>
  </div>

  @stop

resources/views/admin/products/edit.blade.php
@extends('adminlte::page')

@section('title', 'Update Product')

@section('content')

<x-alert />

<div class="card">
      <div class="card-header ">
          <h3 class="card-title text-bold">Update Product</h3>
          <div class="card-tools">
            <a href="{{ route('admin.products.index') }}" class="btn btn-primary btn-sm">
            Go Back
        </a>
          </div>
      </div>
      <div class="card-body" >
           <form action="{{ route('admin.products.update', $product->id) }}" method="Post">
             @csrf
             @method('PUT')

             <div class="form-group">
                <label for="name">Name</label>
                <input
                    type="text"
                    name="name" id="name"
                    value="{{ old('name') ?? $product->name }}"
                    class="form-control @error('name') is-invalid @enderror"
                >
                @error('name')
                <small class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="price">Price</label>
                <input
                    type="number"
                    name="price" id="price"
                    value="{{ old('price') ?? $product->price }}"
                    class="form-control @error('price') is-invalid @enderror"
                >
                @error('price')
                <small class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="description">Description</label>
                <textarea
                    name="description" id="description"
                    value="{{ old('description') ?? '' }}"
                    class="form-control @error('description') is-invalid @enderror"
                >{{ $product->description }}</textarea>
                @error('description')
                <small class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>


                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-fw fa-save mr-1"></i>
                    Save
                </button>

            </form>

        </div>
  </div>

  @stop

resources/views/admin/products/index.blade.php
@extends('adminlte::page')

@section('title', 'All Products')

@section('content')

{{-- @dd($products) --}}

<x-alert />
<x-delete />

<div class="card">
      <div class="card-header ">
          <h3 class="card-title text-bold">All Products</h3>
          <div class="card-tools">
            <a href="{{ route('admin.products.create') }}" class="btn btn-primary btn-sm">
            Add New Product
        </a>
          </div>
      </div>
      <div class="card-body p-0 " >
          <table class="table table-bordered table-striped">
              <thead class="thead-dark">
                  <tr>
                      <th>Id</th>
                      <th>Name</th>
                      <th>Price</th>
                      <th>Action</th>
                  </tr>
              </thead>
              <tbody>
                  @foreach($products as $product )
                  <tr>
                      <td> {{ $product->id }}</td>
                      <td> {{ $product->name }}</td>
                      <td> {{ $product->price }}</td>
                      <td>
                          <a href="{{ route('admin.products.show', $product->id) }} " class="btn btn-secondary btn-sm">
                            Details
                        </a>

                        <a href="{{ route('admin.products.edit', $product->id) }} " class="btn btn-primary btn-sm">
                            Edit
                        </a>

                        <button class="btn btn-danger btn-sm" onclick="confirmDelete({{ $product->id }})">
                            Delete
                        </button>

                        <form id="delete-form-{{ $product->id }}" action="{{ route('admin.products.destroy', $product->id) }}" method="POST" style="display:none">
                            @csrf @method('DELETE')
                        </form>
                      </td>
                  </tr>
                  @endforeach
              </tbody>
          </table>

          {{-- if no items --}}
          @if (count($products)==0)
          <div class="alert alert-warning m-0 text-center">
              No items found!
          </div>
          @endif


        </div>
        @if ($products->perPage() < $products->total() )

       <div class="card-footer">
        {{ $products->links() }}
       </div>

        @endif
  </div>
@stop

resources/views/admin/products/media.blade.php
@extends('adminlte::page')

@section('title', 'Product Images')

@section('content')

    <x-alert/>
    <x-delete/>

    <div class="card">
        <div class="card-header">

            <h3 class="card-title" style="font-size:1.5em;font-weight: bold">Product Images</h3>
            <div class="card-tools">
                <a class="btn btn-success btn-sm" href="{{ route('admin.products.show', $product->id) }}">
                    <i class="fas fa-arrow-left fa-fw mr-1"></i> Go Back
                </a>
            </div>
        </div>
        <div class="card-body">

            <form method="POST" action="{{ route('admin.products.upload', $product->id) }}"
                  enctype="multipart/form-data">

                @csrf
                @method('PUT')

                <div class="form-group">
                    <label for="image">Image <span title="Required" class="text-danger">*</span></label>
                    <input
                        type="file"
                        name="image" id="image"
                        class="form-control-file @error('image') is-invalid @endif"
                    >

                    @error('image')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <input type="submit" class="btn btn-primary" value="Upload">
            </form>
        </div>
        <div class="card-body p-0">
            <table class="table table-bordered border-top-0">
                <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Path</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>

                @foreach($product->medias as $media)
                    <tr>

                        <td>{{ $media->id }}</td>
                        <td><img src="/storage/{{ $media->path }}" height="70px"></td>
                        <td>{{ $media->name }}</td>
                        <td>{{ $media->path }}</td>

                        <td>
                            <a href="#" onclick="confirmDelete({{ $media->id }})">Delete</a>

                            <form style="display:none" method="POST" id="delete-form-{{ $media->id }}"
                                  action="{{ route('admin.products.removeMedia', $product->id) }}">
                                @csrf
                                @method('DELETE')
                                <input type="hidden" name="media_id" value="{{ $media->id }}">
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop

resources/views/admin/products/show.blade.php
@extends('adminlte::page')

@section('title', 'Product Details')

@section('content')


<div class="card">
      <div class="card-header ">
          <h3 class="card-title text-bold">Product Information</h3>
          <div class="card-tools">
            <a class="btn btn-info btn-sm" href="{{ route('admin.products.media', $product->id) }}">
                <i class="fas fa-image fa-fw mr-1"></i> Image
            </a>

        <a href="{{ route('admin.products.index') }}" class="btn btn-primary btn-sm">
            Go Back
        </a>
          </div>
      </div>
      <div class="card-body p-0 " >

          <table class="table table-bordered table-striped">
            <tr>
                <th width="15%">ID</th>
                <td>{{ $product->id }}</td>
            </tr>
              <tr>
                  <th>Name</th>
                  <td>{{ $product->name }}</td>
              </tr>

              <tr>
                  <th>Price</th>
                  <td>{{ money($product->price) }}</td>
              </tr>
              <tr>
                <th>Description</th>
                <td>{{ $product->description }}</td>
            </tr>

            <tr>
                <th>Images</th>
                <td>
                    @foreach($product->medias as $item)
                    <img src="/storage/{{ $item->path }}" height="70px" class="mr-1">
                    @endforeach
                </td>
            </tr>


          </table>

      </div>
  </div>

  @stop