routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Models\Product;

Route::get('/', [SiteController::class, 'index']);
Route::get('/product', [SiteController::class, 'show']);
Route::middleware('auth')->group(function () {
    Route::get('/home', [SiteController::class, 'home']);



    Route::prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function () {

        Route::get('/', [AdminController::class, 'index'])->name('index');

        Route::resource('users', UserController::class);
        Route::resource('categories', CategoryController::class);

        Route::get('products/{product}/media', [\App\Http\Controllers\Admin\ProductController::class, 'media'])->name('products.media');
        Route::put('products/{product}/media', [\App\Http\Controllers\Admin\ProductController::class, 'mediaUpload'])->name('products.upload');
        Route::delete('products/{product}/media', [\App\Http\Controllers\Admin\ProductController::class, 'removeMedia'])->name('products.removeMedia');
        Route::resource('products', ProductController::class);
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function categoreis()
    {
        return $this->hasMany(Category::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(30);

        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all(); //all(['id','name'])

        return view('admin.categories.create', compact('categories'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([

            'name' => ['required'],
            'category_id' => ['nullable', 'exists:categories,id'],
            
        ]);

        Category::create($data);

        return redirect()->route('admin.categories.index')
        ->with('success', 'Category Created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('admin.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $categories = Category::all();

        return view('admin.categories.edit', compact('category', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $data = $request->validate([
            'name' => ['required'],
            'category_id' => ['nullable', 'exists:categories,id'],
            
        ]);

        $category->update($data);

        return redirect()->route('admin.categories.index')
        ->with('success', 'Category updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('admin.categories.index')
            ->with('success', 'Category Deleted Successfully!');
    }
}

resources/views/admin/categories/create.blade.php
@extends('adminlte::page')

@section('title', 'Create New Category')

@section('plugins.Select2', true)

@section('js')

<script>
    $(document).ready(function(){
        $('#category_id').select2();
    });
</script>

@endsection

@section('content')

<x-alert />

<div class="card">
      <div class="card-header ">
          <h3 class="card-title text-bold">Create New Category</h3>
          <div class="card-tools">
            <a href="{{ route('admin.categories.index') }}" class="btn btn-primary btn-sm">
            Go Back
        </a>
          </div>
      </div>
      <div class="card-body  " >
           <form action="{{ route('admin.categories.store') }}" method="POST">
             @csrf

             <div class="form-group">
                <label for="name">Name</label>
                <input
                    type="text"
                    name="name" id="name"
                    value="{{ old('name') ?? '' }}"
                    class="form-control @error('name') is-invalid @enderror"
                >
                @error('name')
                <small class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

                <div class="form-group">
                    <label for="category_id">Parent Category</label>
                    <select name="category_id" id="category_id" class="form-control @error('category_id') is-invalid @enderror">
                        <option value="">No Parent </option>
                        @foreach ($categories as $item )
                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                        @endforeach
                    </select>

                    @error('category_id')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror

                </div>

                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-fw fa-save mr-1"></i>
                    Save
                </button>

            </form>

        </div>
  </div>

  @stop

resources/views/admin/categories/edit.blade.php
@extends('adminlte::page')

@section('title', 'Update Category')

@section('plugins.Select2', true)

@section('js')

<script>
    $(document).ready(function(){
        $('#category_id').select2();
    });
</script>

@endsection

@section('content')

<x-alert />

<div class="card">
      <div class="card-header ">
          <h3 class="card-title text-bold">Update Category</h3>
          <div class="card-tools">
            <a href="{{ route('admin.categories.index') }}" class="btn btn-primary btn-sm">
            Go Back
        </a>
          </div>
      </div>
      <div class="card-body  " >
           <form action="{{ route('admin.categories.update', $category->id) }}" method="POST">
             @csrf
             @method('PUT')

             <div class="form-group">
                <label for="name">Name</label>
                <input
                    type="text"
                    name="name" id="name"
                    value="{{ old('name') ?? $category->name }}"
                    class="form-control @error('name') is-invalid @enderror"
                >
                @error('name')
                <small class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

                <div class="form-group">
                    <label for="category_id">Parent Category</label>
                    <select name="category_id" id="category_id" class="form-control @error('category_id') is-invalid @enderror">
                        <option value="">No Parent </option>
                        @foreach ($categories as $item )
                        <option
                        value="{{ $item->id }}"
                        @if ($item->id == $category->category_id) selected @endif
                        >{{ $item->name }}</option>
                        @endforeach
                    </select>

                    @error('category_id')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror

                </div>

                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-fw fa-save mr-1"></i>
                    Save
                </button>

            </form>

        </div>
  </div>

  @stop

resources/views/admin/categories/index.blade.php
@extends('adminlte::page')

@section('title', 'All Categories')

@section('content')

{{-- @dd($categories) --}}

<x-alert />
<x-delete />
 
<div class="card">
      <div class="card-header ">
          <h3 class="card-title text-bold">All Categories</h3>
          <div class="card-tools">
            <a href="{{ route('admin.categories.create') }}" class="btn btn-primary btn-sm">
            Add New Category
        </a>
          </div>
      </div>
      <div class="card-body p-0 " >
          <table class="table table-bordered table-striped">
              <thead class="thead-dark">
                  <tr>
                      <th>Id</th>
                      <th>Name</th>
                      <th>Parent</th>
                      <th>Action</th>
                  </tr>
              </thead>
              <tbody>
                  @foreach($categories as $category )   
                  <tr>
                      <td> {{ $category->id }}</td>
                      <td> {{ $category->name }}</td>
                      <td>
                          @if ($category->category_id)
                            <a href="{{ route('admin.categories.show', $category->category_id) }}">
                                {{ $category->category->name }}
                            </a>
                              
                          @endif
                      </td>
                      <td>
                          <a href="{{ route('admin.categories.show', $category->id) }} " class="btn btn-secondary btn-sm">
                            Details
                        </a>

                        <a href="{{ route('admin.categories.edit', $category->id) }} " class="btn btn-primary btn-sm">
                            Edit
                        </a>

                        <button class="btn btn-danger btn-sm" onclick="confirmDelete({{ $category->id }})">
                            Delete
                        </button>

                        <form id="delete-form-{{ $category->id }}" action="{{ route('admin.categories.destroy', $category->id) }}" method="POST" style="display:none">
                            @csrf @method('DELETE')
                        </form>
                      </td>
                  </tr>                   
                  @endforeach
              </tbody>
          </table>

           {{-- if no items --}}
           @if (count($categories)==0)
           <div class="alert alert-warning m-0 text-center">
               No items found!
           </div>       
           @endif


        </div>
        @if ($categories->perPage() < $categories->total() )

       <div class="card-footer">
        {{ $categories->links() }}
       </div>
        
        @endif
  </div>
@stop

resources/views/admin/categories/show.blade.php
@extends('adminlte::page')

@section('title', 'Category Details')

@section('content')

 
<div class="card">
      <div class="card-header ">
          <h3 class="card-title text-bold">Category Information</h3>
          <div class="card-tools">
            <a href="{{ route('admin.categories.index') }}" class="btn btn-primary btn-sm">
            Go Back
        </a>
          </div>
      </div>
      <div class="card-body p-0 " >
          
          <table class="table table-bordered table-striped">
            <tr>
                <th width="15%">ID</th>
                <td>{{ $category->id }}</td>
            </tr>
              <tr>
                  <th>Name</th>
                  <td>{{ $category->name }}</td>
              </tr>
             <tr>
                 <th>Parent</th>
                 <td>
                     @if ($category->category_id)
                         
                     <a href="{{ route('admin.categories.show', $category->category_id) }}">
                        {{ $category->category->name }}
                    </a>
                    @endif
                 </td>
             </tr>
             <tr>
                 <th>Childs</th>
                 <td>
                     @if ($category->categoreis) 
                     {{-- if category have multiple child --}}
                     <ul>
                         @foreach ($category->categoreis as $item)                     

                          <li>
                            <a href="{{ route('admin.categories.show', $item->id) }}">
                                {{ $item->name }}
                            </a>

                          </li>
                         @endforeach
                      </ul>
                         
                     @endif
                 </td>
             </tr>

          </table>
        
      </div>
  </div>

  @stop